# Generated by Django 5.1.4 on 2025-01-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whbs_app', '0003_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='PhoNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='massages',
            field=models.TextField(null=True),
        ),
    ]
