# Generated by Django 5.1.4 on 2025-01-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whbs_app', '0004_alter_msg_phono_alter_msg_massages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='massages',
            new_name='msgs',
        ),
    ]
