# Generated by Django 5.1.4 on 2025-01-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whbs_app', '0006_rename_msgs_msg_msge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
