# Generated by Django 5.1.4 on 2025-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whbs_app', '0007_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='user_image',
            field=models.ImageField(null=True, upload_to='user_Profile/'),
        ),
    ]
