# Generated by Django 5.1.4 on 2025-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whbs_app', '0008_user_register_address_user_register_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
