# Generated by Django 5.1.4 on 2025-01-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whbs_app', '0009_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='user_image',
        ),
    ]
